name: Deploy documentation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change working directory
        run: pwd && cd docs

      - name: Install dependencies
        run: pwd && yarn install

      - name: Deploy documentation
        run: pwd && && ./node_modules/.bin/docusaurus deploy
