name: Deploy documentation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout to docs directory
        run: cd docs

      - name: Install dependencies
        run: npm i -D

      - name: Deploy documentation
        run: ./node_modules/.bin/docusaurus deploy
