name: Deploy documentation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cd docs && yarn install

      - name: Deploy documentation
        run: cd docs && ./node_modules/.bin/docusaurus deploy
