name: Deploy documentation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pwd && cd docs && npm i -D

      - name: Deploy documentation
        run: pwd && cd docs && ./node_modules/.bin/docusaurus deploy
