# This is a basic workflow to help you get started with Actions

name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Install dependencies
      - name: Install dependencies
        run: npm i -D && npm run build

      - name: Builds the project
        run: npm i -D && npm run build

      - name: Run tests
        run: npm i -D && npm run test
